#pragma once

#include <vector>
#include <string>
#include <glm/glm.hpp>
#include <random>

// Single affine transformation with probability
struct IFSTransform {
    float a, b, c;      // x' = a*x + b*y + c
    float d, e, f;      // y' = d*x + e*y + f
    float p;            // Probability
    glm::vec3 color;    // Color for points generated by this transform
};

class IFS {
public:
    IFS();

    bool loadFromFile(const std::string& filename);

    void inline setTransforms(const std::vector<IFSTransform>& transforms) { this->transforms = transforms; };
    const inline std::vector<IFSTransform>& getTransforms() const { return transforms; }

    // Set custom colors for transforms
    void setTransformColors(const std::vector<glm::vec3>& colors);

    // Reset random seed for reproducible results
    void resetSeed(unsigned int seed = 42);

    // Generate fractal points
    // Returns vertices in format: x, y, r, g, b (5 floats per vertex)
    std::vector<float> generateVertices(
        int                 numPoints,
        const glm::vec2&    startPoint = { 0.0f, 0.0f }
    );

    // Get bounding box (estimated from generated points)
    void getBoundingBox(
        int                 numPoints,
        glm::vec2&          minBound,
        glm::vec2&          maxBound
    );

private:
    std::vector<IFSTransform>               transforms;
    std::mt19937                            rng;
    std::uniform_real_distribution<float>   dist;

    // Select transform based on probability
    int selectTransform();

    // Apply transform to point
    glm::vec2 applyTransform(const glm::vec2& point, int transformIndex) const;

    // Default colors for transforms
    static const std::vector<glm::vec3>     defaultColors;
};

